[tasks.build-target]
script_runner = '@shell'
script = '''
echo "Building target..."
cargo rustc --manifest-path ../first-target-solution/Cargo.toml --lib -- \
    -C prefer-dynamic -C passes=sancov-module -C llvm-args=-sanitizer-coverage-level=3 \
    -C llvm-args=-sanitizer-coverage-inline-8bit-counters \
    -C llvm-args=-sanitizer-coverage-prune-blocks=0 -C link-dead-code -C lto=no \
    --emit=dep-info,link
'''
dependencies = ["build-fuzzer"]

[tasks.build-fuzzer]
script_runner = '@shell'
script = '''
echo "Building fuzzer..."
#  cargo rustc -- --extern first_target_solution=$(pwd)/../first-target-solution/target/debug/libfirst_target_solution.a -C link-dead-code
cargo build
'''

[tasks.build-all]
run_task = [{ name = "build-target" }, { name = "build-fuzzer" }]
